### ISSUE TITLE
 docker-compose up --build

### ISSUE THREAD

**Issue by italktothewind** [br4chu/docker-compose-maven-plugin#7]
I want to recreate the command  "docker-compose up --build" that rebuilds the images in the compose defined in the following way:

```
  mv-app:
    hostname: mv-app
    build:
      context: .
      dockerfile: myDockerfile
```

Any advice? Thanks!
